### PR TITLE
Add WPF support

### PR DESCRIPTION
**Pull request by Kudo**
Add RNSqlite2.Net46 project file to WPF and moved out RNSqlite2Module.cs and RNSqlite2Package.cs out as shared code.

Thank @craftzdog and @hnq90 for the great work, that react-native-sqlite-2 is actually the first one RN's database solution on Windows.

### CODE REVIEW

**Comment by craftzdog** [comment]
Cool, man!
@hnq90, would you mind reviewing it? :)

**Comment by hnq90** [comment]
@Kudo It's great :+1:

**Comment by zerglingno1** [comment]
@hnq90 : this okie

**Comment by hnq90** [comment]
@Kudo Thank you. I merged.
@craftzdog Could you please publish new version?

**Comment by hnq90** [comment]
@craftzdog Btw, could you please change the project description because we support Android, iOS and Windows.

**Comment by craftzdog** [comment]
Thanks!
Updated the description and published it as v1.3.0.
Cheers 🚀

**Comment by Kudo** [comment]
Thank you guys for the fast review and publish. Awesome!

**Pull request merged**
