### PR TITLE
RN0.59 iOS need to patch NULL string too now

### PR DESCRIPTION
**Pull request by gaodeng**
fix https://github.com/craftzdog/react-native-sqlite-2/issues/51
RN0.59 iOS  need to patch NULL string too now

### CODE REVIEW

**Comment by craftzdog** [comment]
Looks nice but this is a breaking change for older RNs.
Can you add a version check?

**Comment by gaodeng** [comment]
> Looks nice but this is a breaking change for older RNs.
> Can you add a version check?

☹️ I can't find the public api for RN version

**Comment by craftzdog** [comment]
I could reproduce the issue on RN0.58 but could not on 0.59.1.
Seems like it's been resolved on RN side?

**Comment by craftzdog** [comment]
Reproduction code: https://github.com/craftzdog/react-native-sqlite-2-demo/tree/issue-null-chars

**Comment by gaodeng** [comment]
> I could reproduce the issue on RN0.58 but could not on 0.59.1.
> Seems like it's been resolved on RN side?

It can be reproduce on 0.59.1 with following code
```jsx
<Text >{'Hello \u0000 World'}</Text>

```

**Comment by craftzdog** [comment]
Found that it does not happen when Chrome debugger is enabled. Terrible.

**Comment by craftzdog** [comment]
> `<Text >{'Hello \u0000 World'}</Text>`

This code is nothing to do with sqlite itself.

**Comment by gaodeng** [comment]
> > `<Text >{'Hello \u0000 World'}</Text>`
> 
> This code is nothing to do with sqlite itself.

It's an RN bug.Reported here https://github.com/facebook/react-native/issues/24129

**Comment by craftzdog** [comment]
I guess the issue on sqlite will be also resolved if they think it's a RN bug and got resolved.

**Pull request closed without merging**
