### PR TITLE
Add unscape for macos

### PR DESCRIPTION
**Pull request by ospfranco**
In response to comment on #82

### CODE REVIEW

**Comment by craftzdog** [comment]
Sorry for the slow response.
Check out how to test it: https://github.com/craftzdog/react-native-sqlite-2/pull/82#issuecomment-662211188

**Comment by ospfranco** [comment]
Screenshot 2020-07-22 at 08 52 45

Ran the test inside my app, it doesn't crash, but the output is not quite the same as the screenshot you sent, is this correct?

**Comment by ospfranco** [comment]
if I remove the escaping/unescaping completely for macos, then it renders correctly, but then I'm not sure if I will face #51 again.

Screenshot 2020-07-22 at 09 05 36

I guess for now I can remove the escaping/unescaping and see what happens, and if necessary open another PR

**Comment by craftzdog** [comment]
Seems like macOS `Text` component behaves differently.
In the second screenshot, I suspect that it dropped "\u0000Null" in the database, so I guess escaping nulls is necessary.

I updated the test to stringify data as JSON so that we can see the exact data: https://github.com/craftzdog/react-native-sqlite-2/commit/7b138336b037d0d40fa002767d7fe03a7969f1dc

If it stored/read data properly, you should be able to see "Zero\u0000Null" like so:

Screen Shot 2020-07-22 at 18 14 04

**Comment by ospfranco** [comment]
This is what I see with escaping/unescaping enabled:

Screenshot 2020-07-22 at 14 14 03

this is without escaping/unescaping, sometimes it looks like it hangs:

Screenshot 2020-07-22 at 14 15 16

and sometimes it finishes:

Screenshot 2020-07-22 at 14 16 14

**Comment by ospfranco** [comment]
Actually they both hang sometimes and do not load all the output of the list, but with escaping I can see `Zero\u0000Null` string

**Comment by craftzdog** [comment]
Right. Can you respect formatting?
Now `escapeForIOSAndAndroid` is not a proper name, btw.

**Comment by ospfranco** [comment]
how about now?

**Comment by craftzdog** [comment]
Thanks, LGTM!

**Pull request merged**
